services:
  dod-app:
    image: zfanswer/dify-on-dingtalk:latest
    build:
      context: ../
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./.bots.yaml:/app/.bots.yaml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
